name: inno setup build to .exe
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: iscc "vp_kr installer file/CPPSetupData.iss" /O"out_githubaction" /F"Vox Populi INT"
      - uses: actions/upload-artifact@v4
        with:
          name: "Vox Populi INT"
          path: "out_githubaction/Vox Populi INT.exe"